version: '3'

services:

  # Mongo service that runs the MongoDB server container 
  mongodb:
    image : mongo:4.0.4
    container_name: mongodb
    restart: always
    ports:
    - 27017:27017
#    env_file:
#      - .ods.db.env
    volumes :
     - mongodb:/data/db
    command: mongod

  # ODS service that runs the Maven container
  odsbackend:
    build: .
    env_file:
      - .ods.env
    restart: always
    ports:
      - 8080:8080
    depends_on :
      - mongodb         # ensuring that the Maven container is started only after the mongo-service is up
volumes: 
  mongodb: